### ISSUE TITLE
Checking should not be run for new files.

### ISSUE THREAD

**Issue by wheredevel** [afedchin/xbmctorrent#12]
Having an **unwatched** episode in a season - it will always _check_ before starting the _download_.
It did not happen in previous versions (upgraded from 6.7 to 7.7).
It delays playout for 3-4 minutes. 
And it happens every time - to an accumulated UX it is very bad.

**Comment by wheredevel** [comment]
rutor

**Comment by afedchin** [comment]
if you have a torrent with a few episodes it will always checks previously downloaded data, it didn't occurs before, because such kind of torrent files were played with ace stream. now you can select torrent engine in the addon setting. Select AceStream to return previous behavior.

**Comment by wheredevel** [comment]
But, what is the reason for it to check a file that was never downloaded before?!
Aha! For some reason I see a small file 5-6Mb appearing - although it was never requested to play.
Perhaps, when a previous episode finishes it predownloads the next episode?
Didn't happen before...

**Comment by afedchin** [comment]
It doesn't check files (actually pieces of the whole torrent) which wasn't downloaded and do only for those was downloaded before. torrent2http acts as common torrent app, so its behavior is same.  Unfortunately libtorrent creates small pieces of the files that are in the same part of the file which is downloaded

It didn't happen before because the addon used another torrent engine (AceStream) for torrents with multiple files.

**Comment by wheredevel** [comment]
Is there an issue regarding this on torrent2http? i'd vote there for fixing...

**Comment by afedchin** [comment]
No, there isn't an issue. It's desired behavior. As I said before, you can use another torrent engine.
